const MIN_LENGTH = 0.5; //m
const MAX_LENGTH = 24; //m
const MIN_WIDTH = 0.5; //m
const MAX_WIDTH = 16; //m
const MIN_PLANK_LENGTH = 300; //mm
const MAX_PLANK_LENGTH = 3000; //mm
const MIN_PLANK_WIDTH = 90; //mm;
const MAX_PLANK_WIDTH = 1000; //mm;
const MAX_indentFromWall = 50; //mm
const MIN_ITEMS_IN_PACK = 1;
const MAX_ITEMS_IN_PACK = 20;
const MIN_ROW_OFFSET = 100;
const MIN_MIN_LENGTH = 100;
const KOEF_COMPRESS = 35;
